const GLADIATORS = [
  {
    name: 'Maximus',
    combat: '20',
    durability: '5',
    intelligence: '10',
    power: '5',
    speed: '13',
    strength: '8',
  },
  {
    name: 'Bricius',
    combat: '95',
    durability: '80',
    intelligence: '75',
    power: '72',
    speed: '38',
    strength: '28',
  },
  {
    name: 'Nicolus',
    combat: '95',
    durability: '90',
    intelligence: '63',
    power: '62',
    speed: '53',
    strength: '80',
  },
  {
    name: 'Francius',
    combat: '64',
    durability: '80',
    intelligence: '38',
    power: '24',
    speed: '17',
    strength: '100',
  },
  {
    name: 'Aymericus',
    combat: '64',
    durability: '100',
    intelligence: '38',
    power: '98',
    speed: '25',
    strength: '80',
  },
  {
    name: 'Florius',
    combat: '95',
    durability: '80',
    intelligence: '75',
    power: '72',
    speed: '38',
    strength: '28',
  },
  {
    name: 'Baptus',
    combat: '50',
    durability: '40',
    intelligence: '69',
    power: '37',
    speed: '33',
    strength: '10',
  },
  {
    name: 'Gwenvaelius',
    combat: '55',
    durability: '100',
    intelligence: '88',
    power: '100',
    speed: '83',
    strength: '63',
  },
  {
    name: 'Thomus',
    combat: '65',
    durability: '64',
    intelligence: '50',
    power: '99',
    speed: '53',
    strength: '90',
  },
  {
    name: 'Benitus',
    combat: '64',
    durability: '100',
    intelligence: '63',
    power: '100',
    speed: '12',
    strength: '10',
  },
  {
    name: 'Florius',
    combat: '85',
    durability: '65',
    intelligence: '88',
    power: '100',
    speed: '35',
    strength: '28',
  },
  {
    name: 'Loïcius',
    combat: '40',
    durability: '85',
    intelligence: '50',
    power: '100',
    speed: '100',
    strength: '85',
  },
  {
    name: 'Bastus',
    combat: '90',
    durability: '85',
    intelligence: '60',
    power: '95',
    speed: '100',
    strength: '85',
  },
];

export default GLADIATORS;
